# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Tue Aug 16 15:16:10 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnScriptVersion = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnScriptVersion.sizePolicy().hasHeightForWidth())
        self.btnScriptVersion.setSizePolicy(sizePolicy)
        self.btnScriptVersion.setObjectName("btnScriptVersion")
        self.gridLayout_2.addWidget(self.btnScriptVersion, 1, 1, 1, 1)
        self.btnFirmwareversion_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFirmwareversion_3.sizePolicy().hasHeightForWidth())
        self.btnFirmwareversion_3.setSizePolicy(sizePolicy)
        self.btnFirmwareversion_3.setObjectName("btnFirmwareversion_3")
        self.gridLayout_2.addWidget(self.btnFirmwareversion_3, 2, 0, 1, 1)
        self.btnNand_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNand_3.sizePolicy().hasHeightForWidth())
        self.btnNand_3.setSizePolicy(sizePolicy)
        self.btnNand_3.setObjectName("btnNand_3")
        self.gridLayout_2.addWidget(self.btnNand_3, 2, 1, 1, 1)
        self.btnWifi = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWifi.sizePolicy().hasHeightForWidth())
        self.btnWifi.setSizePolicy(sizePolicy)
        self.btnWifi.setObjectName("btnWifi")
        self.gridLayout_2.addWidget(self.btnWifi, 1, 0, 1, 1)
        self.btnNand = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNand.sizePolicy().hasHeightForWidth())
        self.btnNand.setSizePolicy(sizePolicy)
        self.btnNand.setObjectName("btnNand")
        self.gridLayout_2.addWidget(self.btnNand, 0, 1, 1, 1)
        self.btnFirmwareVersion = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFirmwareVersion.sizePolicy().hasHeightForWidth())
        self.btnFirmwareVersion.setSizePolicy(sizePolicy)
        self.btnFirmwareVersion.setObjectName("btnFirmwareVersion")
        self.gridLayout_2.addWidget(self.btnFirmwareVersion, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.snlabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snlabel.sizePolicy().hasHeightForWidth())
        self.snlabel.setSizePolicy(sizePolicy)
        self.snlabel.setObjectName("snlabel")
        self.horizontalLayout_2.addWidget(self.snlabel)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.autotest = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autotest.sizePolicy().hasHeightForWidth())
        self.autotest.setSizePolicy(sizePolicy)
        self.autotest.setObjectName("autotest")
        self.horizontalLayout_2.addWidget(self.autotest)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 3)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnNand_3.setText(_translate("MainWindow", "NAND3"))
        self.btnFirmwareversion_3.setText(_translate("MainWindow", "Firmwareversion3"))
        self.btnScriptVersion.setText(_translate("MainWindow", "ScriptVersion"))
        self.btnWifi.setText(_translate("MainWindow", "Wifi"))
        self.btnNand.setText(_translate("MainWindow", "NAND"))
        self.btnFirmwareVersion.setText(_translate("MainWindow", "FirmwareVersion"))
        self.snlabel.setText(_translate("MainWindow", "SN Number"))
        self.autotest.setText(_translate("MainWindow", "Auto Test"))

